---
title: "과제_1"
output: html_document
date: "2024-03-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 과제 1주차

```{r cars}
a <- sqrt(2) # 예제 1
b <- exp(5)
c <- log10(20)
d <- log(20)
e <- gamma(5)
f <- abs(-4.5)
g <- round(pi,2)
print(g)
```


```{r cars}
dnorm(x=5 , mean = 5 , sd  =1) # 예제 2
dexp(x=1,rate = 5)
dweibull(x =50 , shape = 80 , scale = 1.5)
```
```{r cars}
A <- 5 # 예제 3
B <- 6
a1 <- 2*A + B^2
a2 <- (A^5)*(3^B)
rm(list = ls())
```




```{r cars}
# 예제 4
Norm<-function(x,mu,sigma){
  value <- 10*(1/(sigma*sqrt(2*pi)))*exp(-((x-mu)^2/(2*sigma^2)))
  return(10*value)
}
Norm(1,1,1)
```

```{r cars}
# 예제 5
x = c(1:100)
y = c(1:100)
sum(x*y)
x = c(1:10)
prod(x)
x = c(1:20)/20
sum(x*rep(pi,20))
```
```{r cars}
# 예제 6
x <- c(1:9)*rep(2,9)
mat <- matrix(x,nrow=3)
dimnames(mat)[[2]] <- c('가','나','다')
dimnames(mat)[[1]] <- c('a','b','c')
print(dimnames(mat))
print(mat[2,3])
print(mat)
```


```{r cars}
# 예제 7
iris
iris[iris$Species == 'virginica',]
```


```{r cars}
# 예제 8
x = c(iris[,3])
y = c(iris$Species)
a = list(x,y)
a
```



```{r cars}
# 예제 9
func_9 <-function(x){
  for(i in 1:dim(x)[1]){
    if (x[i,'Species'] == 'setosa'){
      print(1)
    }
    else if (x[i,'Species'] == 'versicolor'){
      print(2)
    }
    else if (x[i,'Species'] == 'virginica'){
      print(3)
    }
  }
}
func_9(iris)
```
